name: Sync Fork with Upstream

on:
  workflow_run:
    workflows: [create-release]
    types:
      - completed
  workflow_dispatch:
  

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Create Pull Request
        run: |
          echo "HI"
        shell: bash
          
