name: Sync Fork with Upstream

on:
  release:
    types: [published]
  workflow_dispatch:
  

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Create Pull Request
        run: |
          echo "HI"
        shell: bash
          
